### PR TITLE
Conditional Card to display EPA Air Quality

### PR DESCRIPTION
**Pull request by BJReplay**
Hi, I found your write up on how to add the EPA data to home assistant (https://www.loryanstrant.com/2023/07/23/track-air-quality-with-home-assistant-and-epa-data/) and I used it and combined it with this from Adam Kamenek https://github.com/AdamGit69/AQI to create a conditional card that displays the EPA rating and AQI.

Here it is on a dashboard, and below that, shown in edit mode.

I figured I'd contribute this PR so if you get your HACS add-in complete, you've got this as a potential air quality card, or at least an idea.

image

image

### CODE REVIEW

**Comment by loryanstrant** [comment]
Heya, thanks so much for providing this, it looks fantastic!
I never bothered with the AQI setup as unfortunately there's no sensors in Sunbury (which is annoying, as the EPA sensor is about 200m from my house).

The thing with this HACS component is that I actually abandoned it as I don't know how to code in Python. I copied the code from someone else (with his permission), had a colleague start to have a punt at it, and then it fizzled out.
I'll merge the request though, so that as you say, maybe one day if I get this complete it'll have your card in it. :-)

Thanks!

**Comment by BJReplay** [comment]
I don't know how to code in python either, but have copy-pasta skillz and have contributed to a couple of other python based projects, and have copy-pasta'd a service in python, so I might have a bit more of a look at what you have in the repo and see if I can get it to a 0.1 status.

That's annoying re the EPA near you.

I am in St Kilda and have an Ecowitt internal monitor for CO2, PM2.5 and PM10, and noticed over Easter that when we opened up the house for "fresh" air, the internal air quality went down.

That's what set me down the course of looking for sources of data, and being new to the HA world, I looked for a local source to integrate into HA, rather than the more local but less actually based on measurements IQAir. Melbourne is close enough for me to show me what I needed - the burning off and still air was leading to poor air quality.

**Comment by loryanstrant** [comment]
Coming back to this, I'm thinking I'll give creating the integration another go - because I've got stuff like ChatGPT and GitHub Copilot at my disposal - so surely it should be as easy as it's made out to be in the ads. :-)

**Comment by BJReplay** [comment]
As it just turned out, I've just submitted an integration to HACS: https://github.com/BJReplay/ha-solcast-solar.  I have no idea how it works 🤣 - the former owner did a dummy spit and deleted his repo which broke installations of HA that were using it so it has been a quick scramble to get my HA up and running, and get a replacement up and running.  But I now know a bit more about it.  Too little to be useful, but enough to be dangerous.

**Comment by BJReplay** [comment]
I saw you just created a release. 

In order to make the integration installable into HACS, you need to package it into a zip: the easiest way to do that is to add a release action to your repo - e,g, [.github/workflows/re;ease.yml](https://github.com/BJReplay/ha-solcast-solar/tree/v3/.github/workflows/release.yml)

If you take mine as an example, just change all solcast_solar to epa_victoria_air_quality.

Then, having ensured your action is ready to go, publish another release, and the action should automatically create the zip for you and add it to the release.

This is what then allows HACS to find the release zip where it expects it to enable it to download the components to your HACS installation.

**Comment by BJReplay** [comment]
I'm going to add the workflows and actions and create a PR for you - since I've just gone through this.

**Comment by loryanstrant** [comment]
Awesome, thanks so much for your help on this, I really appreciate it!

**Pull request merged**
