### PR TITLE
It works (just)

### PR DESCRIPTION
**Pull request by BJReplay**
Hi @loryanstrant, long time no chat.

I've finally got a chance to look at this, and over the last week, after some long nights, I've got this working (only just).

I don't actually want you (necessarily) to accept this PR just yet, but I figured I'd open it to let you know that I've made progress, and to let you have a look.

If you add https://github.com/BJReplay/EPA_AirQuality_HA as a custom repository into HACS, you can now add EPA as an integration, and it will prompt you for an API Key, use your HA location to find the nearest EPA station, and should set up four sensors (two hourly, two daily), and start polling (currently every five minutes).

I've currently changed the manifest so that HACS looks to my repo rather than yours to speed up my testing.

Still a fair bit of work to go: 

- fixing up the sample YAML to include both hourly and daily AQI status and readings
- moving the images to the custom component folder so they get installed, 
- tuning update frequency, 
- creating AQI sensors based of raw PM2.5 readings (I'm doing this in a template in HA at the moment, it clearly belongs in the integration
- better declarative naming of sensors based on location returned by the EPA site API
- readme
- and some robustness changes

Optionally, but I think I can do it:

- populate a selector in the config flow to list EPA sensor locations for the user to configure, sorted by distance from the users HA location
- Name the service for the EPA site.
 
but, at the moment, it's almost ready for a slightly wider alpha release.

Rough plan is to keep this PR open so we can work on this until you're happy that it's actually ready for a first release.

### CODE REVIEW

**Comment by loryanstrant** [comment]
Holy crap, this amazing, thank you!
I've just installed it in my lab instance to test out, and the experience was great. Very smart getting the location from the latitude and longitude!
In all seriousness, this should be your integration - not mine. You've done all the work building it, I've done practically nothing.
How can we make your repo the primary, and get rid of mine?

**Comment by BJReplay** [comment]
> How can we make your repo the primary, and get rid of mine?

Well, if you don't want to be owner, that's fine - but if you don't mind, I'll still credit you, as it was your idea!

We'd just remove you as an owner from the manifest.json, and that would pretty much be it.

If I get it to the state that it's ready to submit to HACS to add into the default store, we'd submit from my repo.

Let me know your thoughts, and if you want to proceed down that path, I'll kill this PR, and keep working in my repo.

**Comment by BJReplay** [comment]
No worries, I am happy to run with it. I will be back to normal life again this week 🤣, and hopefully normal vision by mid December so that I am not squinting to read.

I will keep you posted on updates.

Plan is roughly as layed out above.

First cab off the rank is AQI sensors, then better naming.

I might get them done this week, but I probably won't get fancy changes to the config flow done until my vision is back to normal.

**Comment by loryanstrant** [comment]
Should I kill off my original repo now?
As in archive or even delete it?
Because I wanted to do a PR on your repo to update the sample card, but it was a problem as I have the original repo.

**Comment by BJReplay** [comment]
> Should I kill off my original repo now?
> As in archive or even delete it?

Yeah, I guess so.  Possibly best to archive rather than delete.

I accidently made an edit to it the other day (sorry), but I figured I was better off leaving it there, rather than backing it out.

I can mark the PR as ready, if you want to get it in sync?

**Comment by BJReplay** [comment]
Ready to merge if you want.

**Comment by loryanstrant** [comment]
Which option should I go with?
image

And do I archive it after the merge?

**Comment by BJReplay** [comment]
Squash and merge will probably be the cleanest - you won't have all the history of my mistakes and errors.

Rebase would be similar.

Entirely up to you if you want to archive (or delete) I am pretty sure that I can exist independently from your repo now.

**Pull request merged**
